language: python
sudo: false

python:
  - "2.7"
  - "3.5"

cache:
  - apt
  - directories:
    - $HOME/.cache/pip  # makes things go fast 2nd time around!

notifications:
  email: false

before_install:
  # Setup anaconda
  - pip install --upgrade pip
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$PATH:$HOME/miniconda2/bin
  - export PYTHONPATH=$HOME/miniconda2/lib/python$TRAVIS_PYTHON_VERSION/site-packages/
  - conda update --yes conda

install: # Install packages
  - echo $PATH
  - echo $PYTHONPATH
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy h5py scipy virtualenv
  - pip install --upgrade pip setuptools
  - pip install nose pep8 pyflakes flake8
  - pip install coverage==3.7.1 python-coveralls nose-cov
  - pip install profilehooks
  - python setup.py install

script: # Run test
  - flake8 nidata --exclude numpy_conversions,_external,example*,diffusion
  - pyflakes `find nidata -name \*.py | egrep -v nidata/core/_external | egrep -v example | egrep -v diffusion | egrep -v numpy_conversions`
  - nosetests --with-coverage --cover-package nidata

after_success: # Calculate coverage
  - coveralls

